package com.waldhauser.tasklist.domain.model;

import jakarta.persistence.*;
import java.util.UUID;

/**
 * The User class represents a user entity in the system.
 * It is a persistent entity mapped to the "users" database table.
 * Each User object corresponds to one record in the database.
 * <p>
 * Key attributes:
 * - id: The unique identifier for the user, generated by the database as a UUID.
 * - name: The unique name of the user, which is required and cannot be null.
 * - password: The password for the user, which is required and cannot be null.
 * <p>
 * This class is designed as part of a user management system that associates users
 * with other entities such as tasks or task lists.
 * <p>
 * Usage considerations:
 * - The id field is generated by the database and should not be manually set.
 * - The name field must be unique and cannot be left null.
 * - The password field is required and must not be null or empty.
 */
@Entity
@Table(name = "users") // set which table to use
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID) // this is jakarta import and generated value UUID bc database sets it
    private UUID id;

    @Column(unique = true, nullable = false)
    private String name;

    @Column(nullable = false)
    private String password;

    // Generate -> Constructors
    public User() {
    }

    public User(UUID id, String name, String password) {
        this.id = id;
        this.name = name;
        this.password = password;
    }

    // One constructor without id bc database sets id
    public User(String name, String password) {
        this.name = name;
        this.password = password;
    }

    // Generate -> Getter and Setter
    // Getters
    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    // Setters
    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    // Generate -> toString (all)

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", password='" + password + '\'' +
                '}';
    }
}
